### ISSUE TITLE
Broken on phpBB 3.3.0

### ISSUE THREAD

**Issue by ashishpatel1992** [ForumHulp/loginwithemail#16]
Getting error 500, disabling the extension resolves the issue.
Server logs:
```
[04-Jun-2020 12:14:39 UTC] PHP Warning:  INSECURE_REDIRECT in /home/site1/public_html/forum/includes/functions.php on line 1743
[04-Jun-2020 12:14:39 UTC] PHP Warning:  INSECURE_REDIRECT in /home/site1/public_html/forum/includes/functions.php on line 1743
[04-Jun-2020 12:15:33 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: The routing file "/home/site1/public_html/forum/ext/forumhulp/loginwithemail/config/routing.yml" contains unsupported keys for "forumhulp_loginwithemail_controller": "pattern". Expected one of: "resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition", "controller". in /home/site1/public_html/forum/vendor/symfony/routing/Loader/YamlFileLoader.php:206
Stack trace:
#0 /home/site1/public_html/forum/vendor/symfony/routing/Loader/YamlFileLoader.php(88): Symfony\Component\Routing\Loader\YamlFileLoader->validate(Array, 'forumhulp_login...', '/home/site1/...')
#1 /home/site1/public_html/forum/vendor/symfony/config/Loader/DelegatingLoader.php(40): Symfony\Component\Routing\Loader\YamlFileLoader->load('ext/forumhulp/l...', 'yaml')
#2 /home/site1/public_html/forum/phpbb/routing/router.php(116): Symfony\Component\Config\Loader\DelegatingLoader->load('ext/forumhulp/l...', 'yaml')
#3 /home/site1/public_html/ in /home/site1/public_html/forum/vendor/symfony/routing/Loader/YamlFileLoader.php on line 206
```

**Comment by millzee01** [comment]
I dont think this works with 3.2.5 either

**Comment by lionel-rowe** [comment]
Even after fixing those errors, I couldn't get this to work on newer versions of phpBB, so I created [Email Login](https://www.phpbb.com/community/viewtopic.php?f=456&p=15844046#p15844046) as an alternative (tested on phpBB 3.3.5+).
